apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tgb-nginx
  namespace: kube-system
spec:
  ipAddressType: ipv4
  networking:
    ingress:
      - from:
          - ipBlock:
              cidr: 172.16.3.0/24
          - ipBlock:
              cidr: 172.16.1.0/24
          - ipBlock:
              cidr: 172.16.2.0/24
        ports:
          - port: http
            protocol: TCP
      - from:
          - ipBlock:
              cidr: 172.16.3.0/24
          - ipBlock:
              cidr: 172.16.1.0/24
          - ipBlock:
              cidr: 172.16.2.0/24
        ports:
          - port: 10254
            protocol: TCP
  serviceRef:
    name: ingress-nginx-controller
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-2:231979338870:targetgroup/TgTeste2/ce1f9e0d6f7e742a
  targetType: ip